Repository nvisionative/nvQuickSite, pull requests merged in 2020-11, with the labels that each got.

#259 Refactor Project
  nvQuickSite/CodePlexRSS.cs
  nvQuickSite/ComboItem.cs
  nvQuickSite/Controllers/DatabaseController.cs
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Controllers/VersionController.cs
  nvQuickSite/Main.cs
  nvQuickSite/Models/Package.cs
  nvQuickSite/Models/Version.cs
  nvQuickSite/MsgBoxYesNoIgnore.cs
  nvQuickSite/Program.cs
  nvQuickSite/Settings.cs
  nvQuickSite/Start.cs
  nvQuickSite/UserSettings.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#261 Resolve issue deleting special files and folders, like .git
  nvQuickSite/Controllers/FileSystemController.cs
Labels: enhancement

#262 Add check for online connectivity and logic based on that check
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Controllers/VersionController.cs
  nvQuickSite/Main.cs
  nvQuickSite/Start.cs
Labels: enhancement

#264 Add SQL Server Authentication User Name to user settings for remembrance
  nvQuickSite/Properties/Settings.Designer.cs
  nvQuickSite/Properties/Settings.settings
  nvQuickSite/Start.cs
  nvQuickSite/app.config
Labels: enhancement

#265 Standardize all dialogs
  nvQuickSite/Controllers/DialogController.cs
  nvQuickSite/Controllers/VersionController.cs
  nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxOk.cs
  nvQuickSite/Controls/Dialogs/MsgBoxOk.resx
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.resx
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.resx
  nvQuickSite/Main.cs
  nvQuickSite/Start.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#267 Add folders for Exceptions classes
  nvQuickSite/Controllers/DatabaseController.cs
  nvQuickSite/Controllers/Exceptions/DatabaseControllerException.cs
  nvQuickSite/Controllers/Exceptions/FileSystemControllerException.cs
  nvQuickSite/Controllers/Exceptions/IISControllerException.cs
  nvQuickSite/Controllers/Exceptions/SiteExistsException.cs
  nvQuickSite/Controllers/Exceptions/VersionControllerException.cs
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/Controllers/VersionController.cs
  nvQuickSite/Exceptions/ReadAndExtractException.cs
  nvQuickSite/Main.cs
  nvQuickSite/Start.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#268 Adds option to delete existing sites
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/DeleteSiteProgress.Designer.cs
  nvQuickSite/DeleteSiteProgress.cs
  nvQuickSite/DeleteSiteProgress.resx
  nvQuickSite/Main.Designer.cs
  nvQuickSite/Start.Designer.cs
  nvQuickSite/Start.cs
  nvQuickSite/ViewExistingSites.Designer.cs
  nvQuickSite/ViewExistingSites.cs
  nvQuickSite/ViewExistingSites.resx
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#270 Resolves cursor appearance issue for the View Existing Sites button
  nvQuickSite/Start.Designer.cs
Labels: enhancement

#272 Updated ViewExistingSites to refine the design
  nvQuickSite/ViewExistingSites.Designer.cs
  nvQuickSite/ViewExistingSites.cs
Labels: enhancement

#273 Add setting for enabling the ability to install local packages
  nvQuickSite/Properties/Settings.Designer.cs
  nvQuickSite/Properties/Settings.settings
  nvQuickSite/Start.Designer.cs
  nvQuickSite/Start.cs
  nvQuickSite/UserSettings.Designer.cs
  nvQuickSite/UserSettings.cs
  nvQuickSite/app.config
Labels: enhancement

#274 Implemented logging in application
  nvQuickSite/Controllers/DatabaseController.cs
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Controllers/VersionController.cs
  nvQuickSite/Main.Designer.cs
  nvQuickSite/Main.cs
  nvQuickSite/Main.resx
  nvQuickSite/Program.cs
  nvQuickSite/Start.cs
  nvQuickSite/UserSettings.Designer.cs
  nvQuickSite/UserSettings.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#277 Refine User Settings UI and fix casing for Logs folder
  nvQuickSite/Program.cs
  nvQuickSite/UserSettings.Designer.cs
Labels: enhancement

#281 Disable min, max, resize for dialogs and move User Settings, View Existing Sites, Delete Sites to Controls namespace
  nvQuickSite/Controllers/Exceptions/VersionControllerException.cs
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Controllers/VersionController.cs
  nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.Designer.cs
  nvQuickSite/Controls/Settings/UserSettings.Designer.cs
  nvQuickSite/Controls/Settings/UserSettings.cs
  nvQuickSite/Controls/Settings/UserSettings.resx
  nvQuickSite/Controls/Sites/DeleteSiteProgress.Designer.cs
  nvQuickSite/Controls/Sites/DeleteSiteProgress.cs
  nvQuickSite/Controls/Sites/DeleteSiteProgress.resx
  nvQuickSite/Controls/Sites/ViewExistingSites.Designer.cs
  nvQuickSite/Controls/Sites/ViewExistingSites.cs
  nvQuickSite/Controls/Sites/ViewExistingSites.resx
  nvQuickSite/Start.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#286 Allows deleting a site that is not started
  nvQuickSite/Controllers/DatabaseController.cs
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/Controls/Sites/DeleteSiteProgress.cs
Labels: bug

#287 Move logging of user settings values to DBG instead of INF
  nvQuickSite/Main.cs
Labels: enhancement

#289 Adds a link to the logs folder in the settings
  nvQuickSite/Controls/Settings/UserSettings.Designer.cs
  nvQuickSite/Controls/Settings/UserSettings.cs
Labels: enhancement

#290 Fixes Typo and adjust logging
  nvQuickSite/Controllers/FileSystemController.cs
  nvQuickSite/Controllers/IISController.cs
  nvQuickSite/Controls/Sites/DeleteSiteProgress.cs
  nvQuickSite/Start.cs
Labels: enhancement

#291 Add winget manifest for 1.4.2
  winget/manifests/1.4.2.yaml
Labels: enhancement

#294 Improve visual and placement of View Logs feature and utilize Hand cursor where appropriate
  nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.Designer.cs
  nvQuickSite/Controls/Settings/UserSettings.Designer.cs
  nvQuickSite/Controls/Settings/UserSettings.cs
  nvQuickSite/Controls/Sites/ViewExistingSites.Designer.cs
  nvQuickSite/Properties/Resources.Designer.cs
  nvQuickSite/Properties/Resources.resx
  nvQuickSite/Resources/._logs-icon.png
  nvQuickSite/Resources/logs-icon.png
  nvQuickSite/Start.Designer.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#295 Update version number to 2.0.0
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
  nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj
Labels: enhancement

#298 Add winget manifest for 2.0.0
  winget/manifests/2.0.0.yaml
Labels: enhancement

#300 Replace antiquated installer with new Wix installer
  nvQuickSite-AllProjects.sln
  nvQuickSite/nvQuickSite.csproj
  nvQuickSiteInstaller/.gitignore
  nvQuickSiteInstaller/images/nvQuickSite-Installer-Banner.jpg
  nvQuickSiteInstaller/nvQuickSiteInstaller.sln
  nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj
  nvQuickSiteWixInstaller/License.rtf
  nvQuickSiteWixInstaller/Product.wxs
  nvQuickSiteWixInstaller/banner.bmp
  nvQuickSiteWixInstaller/dialog.bmp
  nvQuickSiteWixInstaller/nvQuickSiteWixInstaller.wixproj
Labels: bug, enhancement

#303 Update screenshot in README
  README.md
Labels: enhancement

#304 Update heading for README
  README.md
Labels: enhancement

#306 Update version number to 2.1.0
  data/latestVersion.json
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
Labels: enhancement

#307 Add v2.1.0 manifest for WinGet
  winget/manifests/2.1.0.yaml
Labels: enhancement

#309 Release 2.1.0
  README.md
  data/latestVersion.json
  nvQuickSite-AllProjects.sln
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
  nvQuickSite/nvQuickSite.csproj
  nvQuickSiteInstaller/.gitignore
  nvQuickSiteInstaller/images/nvQuickSite-Installer-Banner.jpg
  nvQuickSiteInstaller/nvQuickSiteInstaller.sln
  nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj
  nvQuickSiteWixInstaller/License.rtf
  nvQuickSiteWixInstaller/Product.wxs
  nvQuickSiteWixInstaller/banner.bmp
  nvQuickSiteWixInstaller/dialog.bmp
  nvQuickSiteWixInstaller/nvQuickSiteWixInstaller.wixproj
  winget/manifests/2.0.0.yaml
  winget/manifests/2.1.0.yaml
Labels: maintenance
