Repository nvisionative/nvQuickSite, pull requests merged in 2021-09, with the labels that each got.

#324 Renamed control name for close button in View Existing Sites
  nvQuickSite/Controls/Sites/ViewExistingSites.Designer.cs
  nvQuickSite/Controls/Sites/ViewExistingSites.resx
Labels: enhancement

#325 Made dialog messages be able to word-wrap
  nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.Designer.cs
Labels: bug

#326 Properly sorts versions instead of just alphabetically.
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Models/Package.cs
  nvQuickSite/Start.cs
Labels: enhancement

#327 Merge `develop` into `master` for 2.1.1 release
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNo.Designer.cs
  nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.Designer.cs
  nvQuickSite/Controls/Sites/ViewExistingSites.Designer.cs
  nvQuickSite/Controls/Sites/ViewExistingSites.resx
  nvQuickSite/Models/Package.cs
  nvQuickSite/Start.cs
Labels: maintenance

#331 Increment version and move `usings` into namespace
  nvQuickSite/Models/Package.cs
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
Labels: enhancement, maintenance

#332 Add v2.1.1 manifest for WinGet
  winget/manifests/2.1.1.yaml
Labels: enhancement, maintenance

#333 Second merge of `develop` into `master` for 2.1.1 release
  nvQuickSite/Models/Package.cs
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
  winget/manifests/2.1.1.yaml
Labels: maintenance
