Repository nvisionative/nvQuickSite, pull requests merged in 2025-02, with the labels that each got.

#399 Updated to support having multiple RCs
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Extensions/VersionExtensions.cs
  nvQuickSite/Models/Package.cs
  nvQuickSite/Start.cs
  nvQuickSite/nvQuickSite.csproj
Labels: enhancement

#400 Update version for 2.5.0 release
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
Labels: maintenance

#401 Merged `develop` into `main` for `2.5.0` release
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Extensions/VersionExtensions.cs
  nvQuickSite/Models/Package.cs
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/Start.cs
  nvQuickSite/data/latestVersion.json
  nvQuickSite/nvQuickSite.csproj
Labels: maintenance

#402 Fixed a wrong de-duplication of RCs
  nvQuickSite/Controllers/PackageController.cs
Labels: bug

#403 Updated version for 2.5.1 release
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
Labels: maintenance

#404 Merged `develop` into `main` for `2.5.1` release
  nvQuickSite/Controllers/PackageController.cs
  nvQuickSite/Properties/AssemblyInfo.cs
  nvQuickSite/data/latestVersion.json
Labels: maintenance
